#  spring.main.allow-circular-references
spring:
  main:
    allow-circular-references: true
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
  application:
    name: api-gateway-service
